version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '04:00'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
    allow:
      - dependency-type: 'direct'
      - dependency-type: 'indirect'
    target-branch: 'staging'
